version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 15672:15672
      - 5672:5672
  postgressql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ms-password
      POSTGRES_DB: ms-db
      POSTGRES_USER: ms-user
    volumes:
      - postgressql_dev_data:/var/lib/postgressql
    ports:
      - '5432:5432'

volumes:
  postgressql_dev_data:
